export type StatusConversa = "em_espera" | "em_atendimento" | "resolvida"
export type FiltroVisibilidade = "minhas" | "meu_time" | "todas"
export type FiltroStatus = "todas" | StatusConversa

export interface Conversa {
  id: string
  contato: { nome: string | null; telefone: string }
  ultimaMensagem: { texto: string; horario: string }
  naoLidas: number
  status: StatusConversa
  etiquetas: Array<{ nome: string; cor: string }>
  atribuidaA: string | null
  dataPrimeiroContato: string
}

export const MOCK_CONVERSAS: Conversa[] = [
  {
    id: "1",
    contato: { nome: "Ana Paula Ferreira", telefone: "+55 11 99001-1234" },
    ultimaMensagem: { texto: "Oi! Quero fazer um pedido de 50 caixas de sabão em pó.", horario: "09:42" },
    naoLidas: 3,
    status: "em_espera",
    etiquetas: [{ nome: "Novo cliente", cor: "#3b82f6" }],
    atribuidaA: null,
    dataPrimeiroContato: "15 abr. 2026",
  },
  {
    id: "2",
    contato: { nome: "Mercado Bom Preço", telefone: "+55 11 98002-2345" },
    ultimaMensagem: { texto: "Quando chega o estoque de arroz parboilizado?", horario: "09:31" },
    naoLidas: 1,
    status: "em_atendimento",
    etiquetas: [{ nome: "Recompra", cor: "#10b981" }],
    atribuidaA: "Carlos",
    dataPrimeiroContato: "03 jan. 2026",
  },
  {
    id: "3",
    contato: { nome: "João da Silva", telefone: "+55 21 97003-3456" },
    ultimaMensagem: { texto: "Perfeito, obrigado pelo atendimento!", horario: "09:15" },
    naoLidas: 0,
    status: "resolvida",
    etiquetas: [],
    atribuidaA: "Carlos",
    dataPrimeiroContato: "22 ago. 2025",
  },
  {
    id: "4",
    contato: { nome: null, telefone: "+55 11 96004-4567" },
    ultimaMensagem: { texto: "Vocês entregam para o interior de São Paulo?", horario: "08:58" },
    naoLidas: 2,
    status: "em_espera",
    etiquetas: [],
    atribuidaA: null,
    dataPrimeiroContato: "27 abr. 2026",
  },
  {
    id: "5",
    contato: { nome: "Supermercado Central", telefone: "+55 31 95005-5678" },
    ultimaMensagem: { texto: "Preciso do catálogo atualizado com os preços de atacado para esta semana.", horario: "08:47" },
    naoLidas: 0,
    status: "em_atendimento",
    etiquetas: [{ nome: "VIP", cor: "#f59e0b" }, { nome: "Recompra", cor: "#10b981" }],
    atribuidaA: "Fernanda",
    dataPrimeiroContato: "14 out. 2024",
  },
  {
    id: "6",
    contato: { nome: "Distribuidora Norte", telefone: "+55 92 94006-6789" },
    ultimaMensagem: { texto: "Tudo certo! Vou aguardar a nota fiscal.", horario: "08:30" },
    naoLidas: 0,
    status: "resolvida",
    etiquetas: [{ nome: "Recompra", cor: "#10b981" }],
    atribuidaA: "Fernanda",
    dataPrimeiroContato: "07 fev. 2025",
  },
  {
    id: "7",
    contato: { nome: "Padaria do Bairro", telefone: "+55 11 93007-7890" },
    ultimaMensagem: { texto: "Tem açúcar cristal disponível? Quanto está o saco de 50kg?", horario: "08:12" },
    naoLidas: 4,
    status: "em_espera",
    etiquetas: [{ nome: "Novo cliente", cor: "#3b82f6" }],
    atribuidaA: null,
    dataPrimeiroContato: "25 abr. 2026",
  },
  {
    id: "8",
    contato: { nome: "Roberto Alves", telefone: "+55 21 92008-8901" },
    ultimaMensagem: { texto: "Boa tarde! Qual o prazo mínimo de entrega?", horario: "Ontem" },
    naoLidas: 0,
    status: "em_atendimento",
    etiquetas: [],
    atribuidaA: "Carlos",
    dataPrimeiroContato: "11 mar. 2026",
  },
  {
    id: "9",
    contato: { nome: "Atacadão Oeste", telefone: "+55 11 91009-9012" },
    ultimaMensagem: { texto: "Fechado! Manda o boleto para o e-mail cadastrado.", horario: "Ontem" },
    naoLidas: 0,
    status: "resolvida",
    etiquetas: [{ nome: "VIP", cor: "#f59e0b" }],
    atribuidaA: "Fernanda",
    dataPrimeiroContato: "30 jun. 2024",
  },
  {
    id: "10",
    contato: { nome: "Mercadinho da Esquina", telefone: "+55 31 90010-0123" },
    ultimaMensagem: { texto: "Estou com dúvida sobre o pedido #2847, pode verificar?", horario: "Ontem" },
    naoLidas: 1,
    status: "em_atendimento",
    etiquetas: [{ nome: "Recompra", cor: "#10b981" }],
    atribuidaA: "Carlos",
    dataPrimeiroContato: "18 nov. 2024",
  },
  {
    id: "11",
    contato: { nome: "Maria Conceição", telefone: "+55 85 89011-1234" },
    ultimaMensagem: { texto: "Ok, aguardo o retorno.", horario: "Seg" },
    naoLidas: 0,
    status: "em_espera",
    etiquetas: [],
    atribuidaA: null,
    dataPrimeiroContato: "20 abr. 2026",
  },
  {
    id: "12",
    contato: { nome: "Empório São Jorge", telefone: "+55 41 88012-2345" },
    ultimaMensagem: { texto: "Pode mandar a proposta por aqui mesmo.", horario: "Seg" },
    naoLidas: 0,
    status: "em_atendimento",
    etiquetas: [{ nome: "VIP", cor: "#f59e0b" }],
    atribuidaA: "Fernanda",
    dataPrimeiroContato: "05 dez. 2024",
  },
  {
    id: "13",
    contato: { nome: null, telefone: "+55 11 87013-3456" },
    ultimaMensagem: { texto: "Boa tarde, vi o anúncio de vocês e quero saber mais.", horario: "Seg" },
    naoLidas: 5,
    status: "em_espera",
    etiquetas: [{ nome: "Novo cliente", cor: "#3b82f6" }],
    atribuidaA: null,
    dataPrimeiroContato: "26 abr. 2026",
  },
  {
    id: "14",
    contato: { nome: "Hortifruti da Vila", telefone: "+55 11 86014-4567" },
    ultimaMensagem: { texto: "Preciso de 200 caixas de tomate para esta semana, é possível?", horario: "Sex" },
    naoLidas: 0,
    status: "resolvida",
    etiquetas: [],
    atribuidaA: "Carlos",
    dataPrimeiroContato: "08 jan. 2025",
  },
  {
    id: "15",
    contato: { nome: "Supermercado Família", telefone: "+55 62 85015-5678" },
    ultimaMensagem: { texto: "Combinado! Até amanhã então.", horario: "Sex" },
    naoLidas: 0,
    status: "resolvida",
    etiquetas: [{ nome: "Recompra", cor: "#10b981" }],
    atribuidaA: "Fernanda",
    dataPrimeiroContato: "14 fev. 2025",
  },
  {
    id: "16",
    contato: { nome: "Paulo Mendes", telefone: "+55 81 84016-6789" },
    ultimaMensagem: { texto: "Recebi o pedido, mas faltou 10 unidades do produto X.", horario: "Sex" },
    naoLidas: 2,
    status: "em_atendimento",
    etiquetas: [{ nome: "VIP", cor: "#f59e0b" }, { nome: "Novo cliente", cor: "#3b82f6" }],
    atribuidaA: "Carlos",
    dataPrimeiroContato: "03 abr. 2026",
  },
  {
    id: "17",
    contato: { nome: "Armazém do Zé", telefone: "+55 71 83017-7890" },
    ultimaMensagem: { texto: "Qual a condição de pagamento para pedidos acima de R$ 10.000?", horario: "Qui" },
    naoLidas: 0,
    status: "em_espera",
    etiquetas: [],
    atribuidaA: null,
    dataPrimeiroContato: "24 abr. 2026",
  },
  {
    id: "18",
    contato: { nome: "Mini Mercado Sol", telefone: "+55 11 82018-8901" },
    ultimaMensagem: { texto: "Tudo bem, vou aguardar o contato do gerente.", horario: "Qui" },
    naoLidas: 0,
    status: "em_atendimento",
    etiquetas: [{ nome: "Recompra", cor: "#10b981" }],
    atribuidaA: "Fernanda",
    dataPrimeiroContato: "16 set. 2024",
  },
  {
    id: "19",
    contato: { nome: "Comercial Irmãos Lima", telefone: "+55 91 81019-9012" },
    ultimaMensagem: { texto: "Perfeito, negócio fechado!", horario: "Qua" },
    naoLidas: 0,
    status: "resolvida",
    etiquetas: [{ nome: "VIP", cor: "#f59e0b" }, { nome: "Recompra", cor: "#10b981" }],
    atribuidaA: "Carlos",
    dataPrimeiroContato: "22 mai. 2024",
  },
  {
    id: "20",
    contato: { nome: "Loja do Bairro", telefone: "+55 47 80020-0123" },
    ultimaMensagem: { texto: "Boa tarde! Quero fazer meu primeiro pedido com vocês.", horario: "Ter" },
    naoLidas: 0,
    status: "resolvida",
    etiquetas: [{ nome: "Novo cliente", cor: "#3b82f6" }],
    atribuidaA: "Fernanda",
    dataPrimeiroContato: "21 abr. 2026",
  },
]
